//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPORT()
        {
            this.RESPONSEs = new HashSet<RESPONSE>();
        }
    
        public int reportId { get; set; }
        public int accountId { get; set; }
        public string roomId { get; set; }
        public string equipmentId { get; set; }
        public string statusId { get; set; }
        public string note { get; set; }
        public Nullable<int> reportStatus { get; set; }
        public Nullable<System.DateTime> reportedDate { get; set; }
        public Nullable<bool> isEdit { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        public virtual ROOM ROOM { get; set; }
        public virtual STATUS STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPONSE> RESPONSEs { get; set; }
    }
}
