//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPONSE
    {
        public int responseId { get; set; }
        public int accountId { get; set; }
        public int reportId { get; set; }
        public string message { get; set; }
        public int responseType { get; set; }
        public Nullable<System.DateTime> responsedDate { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual REPORT REPORT { get; set; }
    }
}
