CREATE DATABASE Thiet_Bi_Phong_Hoc
USE Thiet_Bi_Phong_Hoc
CREATE TABLE Room
(
	ID INT IDENTITY PRIMARY KEY,
	Name_Room NVARCHAR(100) NOT NULL DEFAULT 'A'
)
CREATE TABLE Status_SV
(
	ID INT IDENTITY PRIMARY KEY,
	Equipment NVARCHAR(100) NOT NULL DEFAULT 'QUAT',
	Status_ NVARCHAR(100) NOT NULL DEFAULT 'KHONG HD'
)
CREATE TABLE Response
(
	ID INT IDENTITY PRIMARY KEY,
	Massage NVARCHAR(100) NOT NULL DEFAULT 'DA XONG',
	Time_Response DATE NOT NULL DEFAULT GETDATE()
)
CREATE TABLE Account
(
	ID INT IDENTITY PRIMARY KEY,
	Name_Ac NVARCHAR(100) NOT NULL DEFAULT 'HT',
	Class NVARCHAR(50) NOT NULL DEFAULT '19T2',
	Faculty NVARCHAR(50)  NOT NULL DEFAULT 'CNTT',
)
CREATE TABLE Report
(
    ID INT IDENTITY PRIMARY KEY,
	ID_Account INT NOT NULL,
    ID_Room INT NOT NULL,
	ID_Response INT NOT NULL,
	ID_Status INT NOT NULL,
	Time_Response DATE NOT NULL DEFAULT GETDATE(),
    Note NVARCHAR(100) NOT NULL DEFAULT 'Khong co'
	FOREIGN KEY (ID_Room) REFERENCES dbo.Room(ID),
	FOREIGN KEY (ID_Response) REFERENCES dbo.Response(ID),
	FOREIGN KEY (ID_Status) REFERENCES dbo.Status_SV(ID),
	FOREIGN KEY (ID_Account) REFERENCES dbo.Account(ID)
)
CREATE TABLE Login 
(
    ID_SV NVARCHAR(100) PRIMARY KEY,
    Name_SV NVARCHAR(100) NOT NULL DEFAULT N'kk',
    PassWord NVARCHAR(100) NOT NULL DEFAULT 0,
    Type INT NOT NULL DEFAULT 0
)
